# Generated by Django 4.2.16 on 2024-11-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('weight', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Weight')),
                ('cost', models.FloatField(default=0.0, verbose_name='Cost')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='nodecost.node', verbose_name='Parent Node')),
            ],
        ),
    ]
